//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int id { get; set; }
        public int id_teachers { get; set; }
        public int id_department { get; set; }
    
        public virtual Info_department Info_department { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
