//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int id { get; set; }
        public Nullable<int> salary { get; set; }
        public int status { get; set; }
        public int seniority { get; set; }
    
        public virtual Status_Job Status_Job { get; set; }
        public virtual User User { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual Working_staff Working_staff { get; set; }
    }
}
