//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info_department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Info_department()
        {
            this.Departments = new HashSet<Department>();
        }
    
        public int id { get; set; }
        public int id_head { get; set; }
        public string description { get; set; }
        public int building { get; set; }
    
        public virtual Building_info Building_info { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
