//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subjects_list
    {
        public int id { get; set; }
        public int id_student { get; set; }
        public int id_subject { get; set; }
        public Nullable<int> grade { get; set; }
        public Nullable<int> id_teacher { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
