//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SINU
{
    using System;
    using System.Collections.Generic;
    
    public partial class Working_staff
    {
        public int id { get; set; }
        public Nullable<int> desk_assigned { get; set; }
        public string responsability { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
